### ISSUE TITLE
Per Category Permission

### ISSUE THREAD

**Issue by TheIntelloBox** [Rayzr522/DecoHeads#11]
Hello,

Could you add Per Category Permission ? :D 
For example : The Category Pokémon, permission : decoheads.pokemon.

Thanks ! :D

**Comment by foxfirecodes** [comment]
Ah, not a bad idea! I can implement this easily. Should the icon not even show in the categories menu if you don't have access?

**Comment by TheIntelloBox** [comment]
Yes, or, under the categories (and maybe) the heads, there is a variable : "Status".
When you have the permission : Status : Owned. Or Status : Not Permission if you don't have the permission. :)
Tell me if it's good.

**Comment by foxfirecodes** [comment]
Hmmm, a system for buying / earning the heads is also a good idea, but it's completely a different feature. Anyways, I'll get back to you with a beta-build that has per-category permissions soon.

**Comment by TheIntelloBox** [comment]
Okay, perfect.

Yeah, I wanted to create an issue with this system. xD
Please add my head. ;( xD

**Comment by foxfirecodes** [comment]
Haha next goal: In-game head creator.

Maybe I'll put your head in the Misc. category as an easter egg :3

**Comment by TheIntelloBox** [comment]
Yeah, so fantastic. :D 

Yeah, pleeeaaase. xD

**Comment by foxfirecodes** [comment]
I have yet to add per-category permissions (I actually forgot about this feature request) but I did add economy support for heads. (83cbf670806fd35ff7475f4a098d086c6045f7a1)

**Comment by TheIntelloBox** [comment]
Fantastic ! :D Tell me when there is a release. :)

**Comment by foxfirecodes** [comment]
I can give you a snapshot release right now, but the official release may be a few more weeks. I pretty much only have time on the weekends to work on projects like this, and even then, I usually only have a few hours each weekend. But here's a snapshot build, if you want to be a beta tester :P

[DecoHeads-1.6.0-SNAPSHOT.zip](https://github.com/Rayzr522/DecoHeads/files/1671127/DecoHeads-1.6.0-SNAPSHOT.zip)

Please let me know if you have any bugs or problems.

**Comment by TheIntelloBox** [comment]
Fantastic ! :D 

Must I delete the folder DecoHeads ?

**Comment by foxfirecodes** [comment]
No, but your messages file will be backed up and reset. You can then copy over the changed messages from the backup file. The `settings.yml` file will be newly created, and your `heads.yml` file will be updated. **Do not manually edit `heads.yml`.** All editing can be done via the new `/decoheadsadmin` (or just `/dha`) commands.

**Comment by foxfirecodes** [comment]
The ability to purchase heads will have to be a future feature, but per category permissions were added actually quite a while ago. (e1ca684f5a7375019cef4f1b58332ddffbfb7b2c, I forgot to mention it in here :p)

If you would still like the ability to "unlock" heads via money, then please open a separate issue. I'm going to close this issue.
