### ISSUE TITLE
DecoHeads / Maybe : DecoBanners ? :D

### ISSUE THREAD

**Issue by TheIntelloBox** [Rayzr522/DecoHeads#12]
Hello,

You created DecoHeads. But why, don't you create DecoBanners. :D Or implement it into DecoHeads ? :D 
This could be fantastic. :) 

Thanks ! :D

**Comment by foxfirecodes** [comment]
This would be a separate plugin. Not a bad idea. I'll definitely think about it.

**Comment by TheIntelloBox** [comment]
Okay. :)

**Comment by foxfirecodes** [comment]
This isn't really related to DecoHeads, so I'm closing this issue.
