### ISSUE TITLE
Suggestions for plugin.

### ISSUE THREAD

**Issue by AgentSwampy** [Rayzr522/DecoHeads#13]
Few suggestions that I'd love to see added to the plugin are:

1]. Add an economy hook, buy/sell the heads from within the GUI and also add an override permission so staff members can use the heads without paying for them.

2]. Add ability to set custom commands/permissions from within the configuration for each command and permission.

3]. Add the ability to do /dh [name] for people to buy heads that aren't included in the GUI and also the ability to set the price for heads that are bought with this command. (Would be good to have 2 different price changing settings -1 for buying your own head- -1 for buying other people's heads-).

4]. Possibly with these settings, it would be good to put this kind of stuff in a config.yml and the messages in a messages.yml to keep things neat and tidy. (Not really too important or anything, but would be a nice addition).

5]. Would be good to have per-head and per-category permissions so that this plugin would be cool to sell as an EULA friendly perk for servers. For example people could purchase the use of a certain head or category and then it unlocks. For example decoheads.use.headname or decoheads.use.categoryname

6]. Add search support (search bar within the GUI, rather than the command) would be fairly cool also. I've noticed you have 'adding search support' in the to-do list, but just in-case that was the command based search that you were on about.

This is just a copy/paste from the comment I left on Bukkit. Look forward to discussing some potential features with you as I really like using this plugin.

**Comment by foxfirecodes** [comment]
First off, thanks for migrating over to GitHub! It makes my life easier :wink:

Just gonna answer these in the order you listed 'em. 

1. I love the idea, in fact I actually was already planning on it. I have a few other projects and features to work on first, but it's certainly a planned feature. 

2. Did you mean to say "for each head"?

3. Very confused about this one. What heads wouldn't be included in the GUI? And, "other people's heads", what? What does that mean?

4. Again, confused about number 3 so I don't know what settings I would be moving xD
Also I could've sworn that I had the messages in a messages.yml file... didn't I?

5. See DecoHeads issue #11 

6. I believe that **was** referring to the command-searching, but I also want to have a proper GUI for searching. The problem with that is there is _no_ easy way to do that, in fact it's actually crazy difficult. Again, I do plan on doing this. Just not sure how yet. 

I'm pretty sure that the todo list is out of date, I'll have to remember to update that. Thanks for all the suggestions!

**Comment by AgentSwampy** [comment]
Hey, thanks for replying so quickly, sorry for my slow response.
I'll answer these in the same order also :)

2. What I mean in #2 is it would be good to have the ability to customize the actual commands and permission of the plugin itself. The ability to change /decoheads and decoheads.use and any other plugin commands and permissions in the configuration having the option to change those things would be great.

3. What I mean by this one is, rather than solely decoration heads, allow people to do /dh (name) to buy the head of another player or something. Similar to the BuyHead plugin if you want to use that as a reference as to what I mean by this.

4. This was my bad, I didn't check properly, there is a messages.yml, sorry for the mishap on this one :)

Again, thanks for replying so quickly and I hope this has clarified a few things. If you still misunderstand anything, leave another comment and I'll try to reword things :p

**Comment by foxfirecodes** [comment]
2. You can do /heads, so that's pretty customizable... having commands that are modified at runtime is hard, iirc. I'll go talk to @I-Al-Istannen though, he should be able to help me.
3. Ah, I'm sure I could incorporate this. Maybe something along the lines of `/heads player <username>`, and I could have a configurable price. Also yeah, prices are something I plan on for DecoHeads.
4. No problem at all :grin:

**Comment by AgentSwampy** [comment]
Alright sounds good! Thanks for considering! :)

**Comment by TheIntelloBox** [comment]
When now ?

**Comment by foxfirecodes** [comment]
Sorry for vanishing! I got quite sick of Bukkit development for a while (which might be obvious form the large quantities of JavaScript projects on my GitHub now, especially Discord bots), but I'm back now.

I'm considering rewriting (again) most of the internals, but I just wanted to let you know that _development on this has started again, it's not a dead project._ It just happens to be a very very large plugin with code that _works_, but doesn't work **super** well, so I have my work cut out for me :P

**Comment by TheIntelloBox** [comment]
Okay, fine so. :D An update in February maybe ? :D

**Comment by foxfirecodes** [comment]
Hopefully! I'm likely going to rewrite DecoHeads to depend on my WIP library, [CreativelyNamedLib](https://github.com/Rayzr522/CreativelyNamedLib), but it's _heavily_ WIP so I have a few things to clean up there first, and then I have to release CNL itself. But yes, hopefully in February :)

**Comment by TheIntelloBox** [comment]
Okay. :)

**Comment by TheIntelloBox** [comment]
Not in February now ? :(

**Comment by foxfirecodes** [comment]
I'm sorry, I just don't know where to start on this, and I've also got other projects I've been working on. What I need to do is spend an hour or two and just outline the plugin in it's current state and how I want to change it. I'm likely going to have to re-write the command handling, but that hopefully won't be a _huge_ problem.

My goals for the next version are (currently) something like this:
- Add economy support
- Add the ability to add your own head to the heads.yml
- Improve tab-completion

**Comment by TheIntelloBox** [comment]
Okay nice. ^^

**Comment by TheIntelloBox** [comment]
?

**Comment by foxfirecodes** [comment]
Hey, sorry for forgetting about this. My Discord server exploded and it's kept me super busy. I'll get back on this project soon.

**Comment by TheIntelloBox** [comment]
Hey.

Okay. ^^
When, do you think ?

**Comment by foxfirecodes** [comment]
Not sure. Soon. I know a lot of people probably want these features, but it'll take quite a lot of work, and I have other work which gets me money. This is free and something that I do only because I love making free stuff.

**Comment by foxfirecodes** [comment]
1 and 4 have now been implemented. 2 seems a bit unnecessary, but 3, 5, and 6 would be nice. I'm going to close this issue and open those as separate issues. 5 has been half implemented (per-category permissions), but I still need to implement per-head permissions.

Sorry for this taking so long :)
