### ISSUE TITLE
Feature : Add custom messages.

### ISSUE THREAD

**Issue by TheIntelloBox** [Rayzr522/DecoHeads#2]
Hello,

I want to customize the "Previous Page" and the "Next Page" and the title of the gui. 
Please add this ! :)

Thanks. :D

**Comment by foxfirecodes** [comment]
Sure, I can localize the messages. Good idea!

**Comment by TheIntelloBox** [comment]
Thanks ! :) Could you add too, a custom messages for "Made with DecoHeads" ? :D

**Comment by foxfirecodes** [comment]
I'll localize _everything_, don't worry. **All** of it 😜

**Comment by TheIntelloBox** [comment]
Thaaanks. :D When do you think ? :D

**Comment by TheIntelloBox** [comment]
Works fine. :) Thanks ! :D

**Comment by foxfirecodes** [comment]
Sorry for not seeing your replies! I'm glad it works well for you :)

**Comment by TheIntelloBox** [comment]
Thanks. :)

**Comment by foxfirecodes** [comment]
Np :)
