### ISSUE TITLE
Update documentation for new permissions. :D

### ISSUE THREAD

**Issue by TheIntelloBox** [Rayzr522/DecoHeads#23]
Hey ! :D

Rayzr must update the Wiki to add the new permissions for each category. :D 

Thanks ! :D

**Comment by foxfirecodes** [comment]
Just fixed.

**Comment by TheIntelloBox** [comment]
Thanks a lot for fixing it fast ! :D 

Have a nice morning or a nice day or a nice evening or a nice night ! :D 
TheIntelloBox. :D
