### ISSUE TITLE
Ability to sell heads

### ISSUE THREAD

**Issue by ShaneSimpkin** [Rayzr522/DecoHeads#27]
Although less of a issue but more of a suggestion. 

I really enjoy DecoHeads and since there is a buying option, it would really be convenient if players could sell the heads too.

**Comment by foxfirecodes** [comment]
Sell them how?

**Comment by foxfirecodes** [comment]
I would love to hear more about how you are imagining this would function, but for the time being, I am going to close the issue until you respond. It is too vague of a suggestion for me to really imagine how this would work.

**Comment by ShaneSimpkin** [comment]
Hi,

Sorry for the late reply. I left the sell part vague as maybe you could attempt a few different ways. However, what would be good is being able to have the buy screen able to sell heads back to the server? or a similar screen much like most GUI style shops. 

I do hope this makes sense, it would just be really good if players could receive money by selling the heads back to the server.

**Comment by foxfirecodes** [comment]
I suppose my real confusion here is what the benefit is. Is the intention that users could get their money back (or some of their money back) for heads that they did not end up needing? Or that users could trade heads almost as a currency and then sell them for money?

How exactly would you intend to use this on your own server? That might help me understand the use case for this.
