### ISSUE TITLE
Allow heads without any lore

### ISSUE THREAD

**Issue by I-Al-Istannen** [Rayzr522/DecoHeads#28]
## Problem
All heads have a lore. If you leave `item.lore` empty you get an empty line, if you set it to null you get `item.lore`.

## Possible fix
Check if the lore is empty and do not split on `\n` in that case, but just skip setting it in the HeadsGui.

## Reported by
`yimyum#2901`  | [Discord message link](https://discordapp.com/channels/282207139752050688/282290090498064384/627617412258332673)

**Comment by foxfirecodes** [comment]
Added in 75da884af390f651190a39c5d8480d0ac69dd860. Download the dev build here: https://ci.rayzr.dev/job/DecoHeads/6/
