### ISSUE TITLE
Permissions Issue

### ISSUE THREAD

**Issue by Aisu-Kohii** [Rayzr522/DecoHeads#34]
I'm trying to add permissions to my permissions plugin on a spigot server, however it doesn't seem to recognise that the permissions have been given.
I've been using the list from the spigot page here: https://github.com/Rayzr522/DecoHeads/wiki/Commands-&-Permissions
this is what my config looks like:
![decoheads permissions](https://user-images.githubusercontent.com/73120804/96462387-6acb6c00-121d-11eb-8a7f-4eb70b2a2682.png)

I don't know if maybe I've just typed them in wrong? For reference, I'm using GroupManager.

**Comment by foxfirecodes** [comment]
GroupManager is incredibly outdated, I'd recommend LuckPerms. i can't really comment on the functionality of GroupManager

**Comment by Aisu-Kohii** [comment]
I switched over to LuckPerms and got decoheads working.
Thank you.
