### ISSUE TITLE
Add a Page Bar

### ISSUE THREAD

**Issue by TheIntelloBox** [Rayzr522/DecoHeads#4]
Hello,

This could be fantastic if we can go to a specific page, because it's too long to search the page 35 for example. :D 

Thanks ! :D

**Comment by foxfirecodes** [comment]
Sorry, there was a bug with the Commands & Permissions page. I fixed it, so [as you can see](https://github.com/Rayzr522/DecoHeads/wiki/Commands-&-Permissions) you can go to any page you want via `/heads <page #>`
