### ISSUE TITLE
Ui issue on server

### ISSUE THREAD

**Issue by Obliviatejj** [Rayzr522/DecoHeads#41]
It works fine for adminis, we open up the ui and can see all the heads. Our players open the ui click on a category but can't see any of the heads to choose from, they have all the permissions to use it.
![20210906_221105](https://user-images.githubusercontent.com/90731384/133343993-f2530e34-5827-4064-a2a6-a117e5f927af.jpg)

**Comment by foxfirecodes** [comment]
this is a permissions issue. please check the [permissions wiki page](https://github.com/Rayzr522/DecoHeads/wiki/Commands-&-Permissions) again. your players need `decoheads.head.*` to get all heads. also note that it is singular "head", NOT plural "heads"
