### ISSUE TITLE
Placing head + chat issue

### ISSUE THREAD

**Issue by alphabeticalDCB** [Rayzr522/DecoHeads#42]
I'm having a huge issue when players place heads. When doing so, the chat is filled with a big chunk of text in chat. Could there be any possible remedy for this?
![Screenshot_2](https://user-images.githubusercontent.com/99226508/152896685-d5b197b6-6a0d-4a47-8004-bd13ae02fcb5.png)
![Screenshot_3](https://user-images.githubusercontent.com/99226508/152896687-289e369b-febd-43df-aaed-138915f4d032.png)

**Comment by foxfirecodes** [comment]
what plugins do you have installed? that doesnt look like it's coming from decoheads, it looks like some kind of debug message presumably from another plugin

**Comment by alphabeticalDCB** [comment]
I have quite a few. Apologies for assuming the issue came from decorheads itself, these messages only ever appear when a head from the plugin is placed down. I can understand why it can come from another plugin though. Here are the complete list of plugins!
![Screenshot_4](https://user-images.githubusercontent.com/99226508/152906569-98a2d5c0-e86b-465c-8ee9-173457e39eb1.png)

**Comment by foxfirecodes** [comment]
you have DecorHeads. this is the DecoHeads repository (no R!) :P

I believe you are in the wrong place! :)
