### ISSUE TITLE
Customize colors codes of the heads.

### ISSUE THREAD

**Issue by TheIntelloBox** [Rayzr522/DecoHeads#6]
Hello ! :D 

The heads are in English, could we add that we can customize the name of the heads in a file ?
And could you add a customize color codes. (now it's &e and &n but if I want to put &c and &l I can't).

Thanks for your work. :)
TheIntelloBox.

**Comment by foxfirecodes** [comment]
Customizing the head colors is possible in the new messages.yml file, and changing the head names was always possible in the heads config file (which is now heads.yml as of v1.3.1)

If you haven't gotten the update for DecoHeads yet, get it now as it has all of these features :P

You might have to go to spigotmc.org to get it as I have to wait for the update to be approved on Bukkit

**Comment by foxfirecodes** [comment]
Only thing I have to say is you might have to put the head names inside quotes if you use letters with accents, like ë or ã. I'm not sure if YAML can support those kinds of letters without quotations.

**Comment by TheIntelloBox** [comment]
Thanks. :D 

I have a question. xD Could you add my head in your plugin because I suggested many features ? xDD

**Comment by foxfirecodes** [comment]
Maybe :P

Also I will be adding a tool for creating your own custom heads either in v1.4 or v1.5. It depends on how difficult it ends up being.

**Comment by foxfirecodes** [comment]
So is this issue solved? If so, I will close it.

**Comment by TheIntelloBox** [comment]
Oh thanks. :P 

Oh fantastic !
Yes it's fixed.

**Comment by foxfirecodes** [comment]
Awesome :)
