### ISSUE TITLE
(Soon) 1.11 support.

### ISSUE THREAD

**Issue by TheIntelloBox** [Rayzr522/DecoHeads#7]
Hello,

The title says all. :D 
The bukkit and spigot 1.11 version is out on the 19th or on the 20th of November 2016. :D 
So, please add 1.11 support when this is available. :D 

Thanks. :)

**Comment by foxfirecodes** [comment]
You're opening an issue for something I can't fix (it hasn't been released yet)?

GG 😛

**Comment by foxfirecodes** [comment]
Also I may not have to do ANYTHING to make it compatible with 1.11, that entirely depends on if they changed the internals which my plugin interacts with.

**Comment by TheIntelloBox** [comment]
It is in forecast. As I said in the title : Soon.
Yes maybe. x)

**Comment by TheIntelloBox** [comment]
Spigot 1.11 available, so check please. :D

**Comment by foxfirecodes** [comment]
I saw, and I'll take a look to see if it's still compatible with my plugin shortly.

**Comment by foxfirecodes** [comment]
Everything seems to be 100% compatible with 1.11
