### ISSUE TITLE
Add heads with a command

### ISSUE THREAD

**Issue by TheIntelloBox** [Rayzr522/DecoHeads#9]
Hello,

Could you add a system (it's important I think), where we can add heads that are not in the plugin, with a command. You must have the head in your hand to do the command.
For example : I have a christmas head, and I type /heads addhead !

Thanks ! :)

**Comment by foxfirecodes** [comment]
I don't know if it's possible, it would depend on the data of the head...

I'm already planning on making it so you can save your current skin as a permanent head, which would allow you to create custom heads more easily. I'm not sure if I can retrieve the data from a player head though... I'll look into it :smile:

**Comment by TheIntelloBox** [comment]
Great ! :) It's a good feature. :)

Could you add Christmas and Winter heads in your future update please ? :D Like gift, snowman... x) !

**Comment by foxfirecodes** [comment]
I will begin doing that once I have an in-game head creator and a categories system 😛

**Comment by TheIntelloBox** [comment]
:D. Yep. :)

**Comment by foxfirecodes** [comment]
Alright, categories system is out in v1.4. This is my next big goal, although before I can get to it I have other projects to work on.

**Comment by TheIntelloBox** [comment]
Perfect.

**Comment by TheIntelloBox** [comment]
Any news ? :(

**Comment by foxfirecodes** [comment]
Sorry, I keep getting behind on projects! I will get to this, I promise.

**Comment by TheIntelloBox** [comment]
Okay. :) Thanks again ! :)

**Comment by foxfirecodes** [comment]
How does this sound?

`/decoheadsadmin add hand <name>`
> Adds the head you are currently holding under the given name

`/decoheadsadmin add self <name>`
> Adds your current skin as a head under the given name

I'm not entirely sure if the `self` one will be easily possible, but it should be.

**Comment by TheIntelloBox** [comment]
Yeah that's nice.

**Comment by foxfirecodes** [comment]
Added in e12dfc46ec4cbf43b0723c25ef33b7829c68d51a.
